services:
    sonata.admin.tournament.tournament:
        class: InsaLan\TournamentBundle\Admin\TournamentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tournois", label: "Tournoi" }
        arguments:
            - ~
            - InsaLan\TournamentBundle\Entity\Tournament
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanTournamentBundle]]

    sonata.admin.tournament.groupstage:
        class: InsaLan\TournamentBundle\Admin\GroupStageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tournois", label: "Phase poules" }
        arguments:
            - ~
            - InsaLan\TournamentBundle\Entity\GroupStage
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanTournamentBundle]]

    sonata.admin.tournament.group:
        class: InsaLan\TournamentBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tournois", label: "Poule" }
        arguments:
            - ~
            - InsaLan\TournamentBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanTournamentBundle]]

    sonata.admin.tournament.player:
        class: InsaLan\TournamentBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tournois", label: "Joueur" }
        arguments:
            - ~
            - InsaLan\TournamentBundle\Entity\Player
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanTournamentBundle]]

    sonata.admin.tournament.team:
        class: InsaLan\TournamentBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tournois", label: "Equipes" }
        arguments:
            - ~
            - InsaLan\TournamentBundle\Entity\Team
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanTournamentBundle]]

    insalan.tournament.participant_validator:
        class: InsaLan\TournamentBundle\Subscriber\ParticipantValidator
        arguments: [@insalan.free_slots]
        tags:
            - { name: doctrine.event_subscriber }
    
    insalan.pvp_net:
        class: InsaLan\TournamentBundle\Service\PvpNet
        arguments: [@insalan.lol]
